name: "Learning Pipelines with GitHub Actions - Deploy"

run-name: ${{ github.actor }} is learning pipelines with GitHub Actions

on:
  push:
    branches: [prod]

jobs:
  deploy: # Ajout d'un nom de job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Make tests
        run: pnpm test

      - name: Deploy Completed
        run: echo "Deploying to production completed successfully"
